# Lab1_S3 examples

In [5]:
#Installing Gensim library
!pip install gensim
!pip install nltk

Requirement already satisfied: gensim in /usr/local/lib/python3.11/dist-packages (4.3.3)
Requirement already satisfied: numpy<2.0,>=1.18.5 in /usr/local/lib/python3.11/dist-packages (from gensim) (1.26.4)
Requirement already satisfied: scipy<1.14.0,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from gensim) (1.13.1)
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim) (7.1.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim) (1.17.2)
Requirement already satisfied: nltk in /usr/local/lib/python3.11/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.11/dist-packages (from nltk) (8.1.8)
Requirement already satisfied: joblib in /usr/local/lib/python3.11/dist-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.11/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from nltk) (4.67.1)

## Load the corpus

In [6]:
import pandas as pd

In [7]:
path = "EXIST2024_EN_examples.csv"
df = pd.read_csv(path, sep="\t")
df

          id                                               text label  size
0     200002  Writing a uni essay in my local pub with a cof...   YES   255
1     200003  @UniversalORL it is 2021 not 1921. I dont appr...   YES   191
2     200006  According to a customer I have plenty of time ...   YES   183
3     200007  So only 'blokes' drink beer? Sorry, but if you...   YES   197
4     200008  New to the shelves this week - looking forward...    NO   172
...      ...                                                ...   ...   ...
2847  203256  idk why y’all bitches think having half your a...   YES   143
2848  203257  This has been a part of an experiment with @Wo...   YES   278
2849  203258  "Take me already" "Not yet. You gotta be ready...   YES   264
2850  203259  @clintneedcoffee why do you look like a whore?...   YES    74
2851  203260  ik when mandy says “you look like a whore” i l...   YES    62

[2852 rows x 4 columns]

In [ ]:
# OR USING Google colab
#from google.colab import drive
#drive.mount('/content/drive')
#path = "/content/drive/MyDrive/LNR/LNR2025/Lab1/EXIST2024_EN_examples.csv"
#df = pd.read_csv(path, sep="\t")
#df

###EXAMPLE 1: Listing the pre-trained word-embeddings in Gensim

In [9]:
#Listing the pretained embeddings available on Gensim
import gensim.downloader as api
info = api.info()
for item in info["models"].items():
   print (item)

('fasttext-wiki-news-subwords-300', {'num_records': 999999, 'file_size': 1005007116, 'base_dataset': 'Wikipedia 2017, UMBC webbase corpus and statmt.org news dataset (16B tokens)', 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/fasttext-wiki-news-subwords-300/__init__.py', 'license': 'https://creativecommons.org/licenses/by-sa/3.0/', 'parameters': {'dimension': 300}, 'description': '1 million word vectors trained on Wikipedia 2017, UMBC webbase corpus and statmt.org news dataset (16B tokens).', 'read_more': ['https://fasttext.cc/docs/en/english-vectors.html', 'https://arxiv.org/abs/1712.09405', 'https://arxiv.org/abs/1607.01759'], 'checksum': 'de2bb3a20c46ce65c9c131e1ad9a77af', 'file_name': 'fasttext-wiki-news-subwords-300.gz', 'parts': 1})
('conceptnet-numberbatch-17-06-300', {'num_records': 1917247, 'file_size': 1225497562, 'base_dataset': 'ConceptNet, word2vec, GloVe, and OpenSubtitles 2016', 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/conceptnet-numberbatch-17-06-300/__init__.py', 'license': 'https://github.com/commonsense/conceptnet-numberbatch/blob/master/LICENSE.txt', 'parameters': {'dimension': 300}, 'description': 'ConceptNet Numberbatch consists of state-of-the-art semantic vectors (also known as word embeddings) that can be used directly as a representation of word meanings or as a starting point for further machine learning. ConceptNet Numberbatch is part of the ConceptNet open data project. ConceptNet provides lots of ways to compute with word meanings, one of which is word embeddings. ConceptNet Numberbatch is a snapshot of just the word embeddings. It is built using an ensemble that combines data from ConceptNet, word2vec, GloVe, and OpenSubtitles 2016, using a variation on retrofitting.', 'read_more': ['http://aaai.org/ocs/index.php/AAAI/AAAI17/paper/view/14972', 'https://github.com/commonsense/conceptnet-numberbatch', 'http://conceptnet.io/'], 'checksum': 'fd642d457adcd0ea94da0cd21b150847', 'file_name': 'conceptnet-numberbatch-17-06-300.gz', 'parts': 1})
('word2vec-ruscorpora-300', {'num_records': 184973, 'file_size': 208427381, 'base_dataset': 'Russian National Corpus (about 250M words)', 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/word2vec-ruscorpora-300/__init__.py', 'license': 'https://creativecommons.org/licenses/by/4.0/deed.en', 'parameters': {'dimension': 300, 'window_size': 10}, 'description': 'Word2vec Continuous Skipgram vectors trained on full Russian National Corpus (about 250M words). The model contains 185K words.', 'preprocessing': 'The corpus was lemmatized and tagged with Universal PoS', 'read_more': ['https://www.academia.edu/24306935/WebVectors_a_Toolkit_for_Building_Web_Interfaces_for_Vector_Semantic_Models', 'http://rusvectores.org/en/', 'https://github.com/RaRe-Technologies/gensim-data/issues/3'], 'checksum': '9bdebdc8ae6d17d20839dd9b5af10bc4', 'file_name': 'word2vec-ruscorpora-300.gz', 'parts': 1})
('word2vec-google-news-300', {'num_records': 3000000, 'file_size': 1743563840, 'base_dataset': 'Google News (about 100 billion words)', 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/word2vec-google-news-300/__init__.py', 'license': 'not found', 'parameters': {'dimension': 300}, 'description': "Pre-trained vectors trained on a part of the Google News dataset (about 100 billion words). The model contains 300-dimensional vectors for 3 million words and phrases. The phrases were obtained using a simple data-driven approach described in 'Distributed Representations of Words and Phrases and their Compositionality' (https://code.google.com/archive/p/word2vec/).", 'read_more': ['https://code.google.com/archive/p/word2vec/', 'https://arxiv.org/abs/1301.3781', 'https://arxiv.org/abs/1310.4546', 'https://www.microsoft.com/en-us/research/publication/linguistic-regularities-in-continuous-space-word-representations/?from=http%3A%2F%2Fresearch.microsoft.com%2Fpubs%2F189726%2Frvecs.pdf'], 'checksum': 'a5e5354d40acb95f9ec66d5977d140ef', 'file_name': 'word2vec-google-news-300.gz', 'parts': 1})
('glove-wiki-gigaword-50', {'num_records': 400000, 'file_size': 69182535, 'base_dataset': 'Wikipedia 2014 + Gigaword 5 (6B tokens, uncased)', 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-wiki-gigaword-50/__init__.py', 'license': 'http://opendatacommons.org/licenses/pddl/', 'parameters': {'dimension': 50}, 'description': 'Pre-trained vectors based on Wikipedia 2014 + Gigaword, 5.6B tokens, 400K vocab, uncased (https://nlp.stanford.edu/projects/glove/).', 'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-wiki-gigaword-50.txt`.', 'read_more': ['https://nlp.stanford.edu/projects/glove/', 'https://nlp.stanford.edu/pubs/glove.pdf'], 'checksum': 'c289bc5d7f2f02c6dc9f2f9b67641813', 'file_name': 'glove-wiki-gigaword-50.gz', 'parts': 1})
('glove-wiki-gigaword-100', {'num_records': 400000, 'file_size': 134300434, 'base_dataset': 'Wikipedia 2014 + Gigaword 5 (6B tokens, uncased)', 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-wiki-gigaword-100/__init__.py', 'license': 'http://opendatacommons.org/licenses/pddl/', 'parameters': {'dimension': 100}, 'description': 'Pre-trained vectors based on Wikipedia 2014 + Gigaword 5.6B tokens, 400K vocab, uncased (https://nlp.stanford.edu/projects/glove/).', 'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-wiki-gigaword-100.txt`.', 'read_more': ['https://nlp.stanford.edu/projects/glove/', 'https://nlp.stanford.edu/pubs/glove.pdf'], 'checksum': '40ec481866001177b8cd4cb0df92924f', 'file_name': 'glove-wiki-gigaword-100.gz', 'parts': 1})
('glove-wiki-gigaword-200', {'num_records': 400000, 'file_size': 264336934, 'base_dataset': 'Wikipedia 2014 + Gigaword 5 (6B tokens, uncased)', 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-wiki-gigaword-200/__init__.py', 'license': 'http://opendatacommons.org/licenses/pddl/', 'parameters': {'dimension': 200}, 'description': 'Pre-trained vectors based on Wikipedia 2014 + Gigaword, 5.6B tokens, 400K vocab, uncased (https://nlp.stanford.edu/projects/glove/).', 'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-wiki-gigaword-200.txt`.', 'read_more': ['https://nlp.stanford.edu/projects/glove/', 'https://nlp.stanford.edu/pubs/glove.pdf'], 'checksum': '59652db361b7a87ee73834a6c391dfc1', 'file_name': 'glove-wiki-gigaword-200.gz', 'parts': 1})
('glove-wiki-gigaword-300', {'num_records': 400000, 'file_size': 394362229, 'base_dataset': 'Wikipedia 2014 + Gigaword 5 (6B tokens, uncased)', 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-wiki-gigaword-300/__init__.py', 'license': 'http://opendatacommons.org/licenses/pddl/', 'parameters': {'dimension': 300}, 'description': 'Pre-trained vectors based on Wikipedia 2014 + Gigaword, 5.6B tokens, 400K vocab, uncased (https://nlp.stanford.edu/projects/glove/).', 'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-wiki-gigaword-300.txt`.', 'read_more': ['https://nlp.stanford.edu/projects/glove/', 'https://nlp.stanford.edu/pubs/glove.pdf'], 'checksum': '29e9329ac2241937d55b852e8284e89b', 'file_name': 'glove-wiki-gigaword-300.gz', 'parts': 1})
('glove-twitter-25', {'num_records': 1193514, 'file_size': 109885004, 'base_dataset': 'Twitter (2B tweets, 27B tokens, 1.2M vocab, uncased)', 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-twitter-25/__init__.py', 'license': 'http://opendatacommons.org/licenses/pddl/', 'parameters': {'dimension': 25}, 'description': 'Pre-trained vectors based on 2B tweets, 27B tokens, 1.2M vocab, uncased (https://nlp.stanford.edu/projects/glove/).', 'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-twitter-25.txt`.', 'read_more': ['https://nlp.stanford.edu/projects/glove/', 'https://nlp.stanford.edu/pubs/glove.pdf'], 'checksum': '50db0211d7e7a2dcd362c6b774762793', 'file_name': 'glove-twitter-25.gz', 'parts': 1})
('glove-twitter-50', {'num_records': 1193514, 'file_size': 209216938, 'base_dataset': 'Twitter (2B tweets, 27B tokens, 1.2M vocab, uncased)', 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-twitter-50/__init__.py', 'license': 'http://opendatacommons.org/licenses/pddl/', 'parameters': {'dimension': 50}, 'description': 'Pre-trained vectors based on 2B tweets, 27B tokens, 1.2M vocab, uncased (https://nlp.stanford.edu/projects/glove/)', 'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-twitter-50.txt`.', 'read_more': ['https://nlp.stanford.edu/projects/glove/', 'https://nlp.stanford.edu/pubs/glove.pdf'], 'checksum': 'c168f18641f8c8a00fe30984c4799b2b', 'file_name': 'glove-twitter-50.gz', 'parts': 1})
('glove-twitter-100', {'num_records': 1193514, 'file_size': 405932991, 'base_dataset': 'Twitter (2B tweets, 27B tokens, 1.2M vocab, uncased)', 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-twitter-100/__init__.py', 'license': 'http://opendatacommons.org/licenses/pddl/', 'parameters': {'dimension': 100}, 'description': 'Pre-trained vectors based on  2B tweets, 27B tokens, 1.2M vocab, uncased (https://nlp.stanford.edu/projects/glove/)', 'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-twitter-100.txt`.', 'read_more': ['https://nlp.stanford.edu/projects/glove/', 'https://nlp.stanford.edu/pubs/glove.pdf'], 'checksum': 'b04f7bed38756d64cf55b58ce7e97b15', 'file_name': 'glove-twitter-100.gz', 'parts': 1})
('glove-twitter-200', {'num_records': 1193514, 'file_size': 795373100, 'base_dataset': 'Twitter (2B tweets, 27B tokens, 1.2M vocab, uncased)', 'reader_code': 'https://github.com/RaRe-Technologies/gensim-data/releases/download/glove-twitter-200/__init__.py', 'license': 'http://opendatacommons.org/licenses/pddl/', 'parameters': {'dimension': 200}, 'description': 'Pre-trained vectors based on 2B tweets, 27B tokens, 1.2M vocab, uncased (https://nlp.stanford.edu/projects/glove/).', 'preprocessing': 'Converted to w2v format with `python -m gensim.scripts.glove2word2vec -i <fname> -o glove-twitter-200.txt`.', 'read_more': ['https://nlp.stanford.edu/projects/glove/', 'https://nlp.stanford.edu/pubs/glove.pdf'], 'checksum': 'e52e8392d1860b95d5308a525817d8f9', 'file_name': 'glove-twitter-200.gz', 'parts': 1})
('__testing_word2vec-matrix-synopsis', {'description': '[THIS IS ONLY FOR TESTING] Word vecrors of the movie matrix.', 'parameters': {'dimensions': 50}, 'preprocessing': 'Converted to w2v using a preprocessed corpus. Converted to w2v format with `python3.5 -m gensim.models.word2vec -train <input_filename> -iter 50 -output <output_filename>`.', 'read_more': [], 'checksum': '534dcb8b56a360977a269b7bfc62d124', 'file_name': '__testing_word2vec-matrix-synopsis.gz', 'parts': 1})

###EXAMPLE 2: Loading pre-trained word embeddings vectors

In [10]:
#Downloading the pre-trained word embedding matrix generated by the Word2Vec method trained on Google News (about 100 billion words)
model = api.load("word2vec-google-news-300")
vec = model.get_vector("woman")
print(vec)

[ 2.43164062e-01 -7.71484375e-02 -1.03027344e-01 -1.07421875e-01
  1.18164062e-01 -1.07421875e-01 -1.14257812e-01  2.56347656e-02
  1.11816406e-01  4.85839844e-02 -9.71679688e-02 -3.43750000e-01
 -6.29882812e-02 -1.25000000e-01 -2.70996094e-02  9.42382812e-02
 -1.87500000e-01 -5.34667969e-02  6.25000000e-02 -3.05175781e-02
 -2.90527344e-02 -4.80957031e-02 -5.51757812e-02 -4.08203125e-01
  1.01318359e-02 -2.32421875e-01 -1.70898438e-01  2.63671875e-01
  3.49609375e-01 -2.11914062e-01  1.43554688e-01 -6.22558594e-03
 -2.25585938e-01 -1.05468750e-01 -1.16210938e-01  1.23046875e-01
  3.06640625e-01 -4.88281250e-02 -9.57031250e-02  1.99218750e-01
 -1.57226562e-01 -2.80761719e-02  1.58203125e-01 -2.42919922e-02
  1.29882812e-01 -8.98437500e-02 -7.61718750e-02  3.54003906e-02
 -3.06396484e-02  1.52343750e-01  5.24902344e-02  1.60980225e-03
  5.56640625e-02  3.95507812e-02 -7.71484375e-02 -7.12890625e-02
 -9.22851562e-02 -7.03125000e-02  2.03125000e-01  1.53198242e-02
  2.98828125e-01  1.75781250e-01 -4.54101562e-02  9.52148438e-02
  4.12597656e-02  7.76367188e-02  9.47265625e-02  1.67968750e-01
  2.01171875e-01 -7.22656250e-02  1.83593750e-01  2.15820312e-01
 -2.38281250e-01  1.04980469e-01 -1.66015625e-02  2.40234375e-01
  1.67236328e-02 -4.56542969e-02  1.68945312e-01  1.85546875e-01
  2.47070312e-01 -1.02050781e-01  8.49609375e-02 -1.04003906e-01
 -4.74609375e-01  2.63671875e-01 -1.57226562e-01  8.25195312e-02
  2.19726562e-01 -3.03955078e-02 -2.55859375e-01 -1.97265625e-01
 -9.27734375e-02 -1.28173828e-02  1.26953125e-01  3.54003906e-02
  5.88378906e-02  3.27148438e-02  1.72851562e-01 -2.08740234e-02
 -1.65039062e-01 -2.81250000e-01  8.49609375e-02 -1.69921875e-01
  2.31445312e-01 -1.41601562e-01  7.91015625e-02 -1.92382812e-01
  7.61718750e-02 -2.23632812e-01 -1.06811523e-02  5.66406250e-02
  1.56250000e-01  7.17773438e-02 -1.56250000e-01 -1.44531250e-01
 -8.30078125e-02 -1.21093750e-01  5.63964844e-02  2.61718750e-01
  7.95898438e-02 -1.28784180e-02 -2.00195312e-01 -4.39453125e-02
 -1.01562500e-01  1.29882812e-01  9.42382812e-02  1.90429688e-02
  1.42578125e-01  1.59179688e-01 -7.47070312e-02 -3.24218750e-01
 -2.07031250e-01  4.80957031e-02 -4.19921875e-02  9.22851562e-02
 -4.39453125e-02 -2.20703125e-01 -6.25000000e-02  8.39843750e-02
  2.29492188e-01 -1.11816406e-01  9.03320312e-02  2.08984375e-01
 -2.28515625e-01  2.87109375e-01 -1.38671875e-01  1.85546875e-01
 -2.10937500e-01 -2.05078125e-01  3.00781250e-01 -1.82617188e-01
  1.23046875e-01 -1.61132812e-01  9.37500000e-02  1.25976562e-01
 -8.10546875e-02  9.15527344e-05  1.53320312e-01 -8.10546875e-02
 -1.93359375e-01  7.08007812e-03  3.84765625e-01  1.05957031e-01
 -1.09375000e-01 -1.13769531e-01  9.13085938e-02 -1.92382812e-01
  6.12792969e-02  6.07299805e-03 -4.54101562e-02  6.25000000e-02
 -1.30859375e-01 -1.83593750e-01 -1.76757812e-01 -1.87500000e-01
  2.44140625e-01  1.89453125e-01 -1.93359375e-01 -2.29492188e-02
  2.53906250e-02  3.93676758e-03 -1.38671875e-01 -2.81250000e-01
 -1.80664062e-01  8.69140625e-02  3.17382812e-02  2.55859375e-01
 -2.30468750e-01 -5.24902344e-02 -2.18200684e-03  1.60156250e-01
  1.57226562e-01  2.79296875e-01  1.37695312e-01  1.04492188e-01
 -1.18652344e-01 -5.81054688e-02 -7.32421875e-02  1.04980469e-02
 -1.77734375e-01 -1.07421875e-01 -1.76757812e-01 -1.23046875e-01
 -1.69921875e-01 -1.34765625e-01  6.39648438e-02  1.22558594e-01
  1.95312500e-01 -4.94140625e-01 -3.90625000e-02 -3.19824219e-02
 -1.58691406e-02 -4.10156250e-02 -1.43554688e-01 -8.59375000e-02
 -7.95898438e-02  2.46093750e-01 -1.77734375e-01  2.05078125e-01
  5.32226562e-02 -2.51464844e-02  2.14843750e-01  2.12402344e-02
  9.76562500e-02 -2.16796875e-01  2.85156250e-01 -1.19140625e-01
 -1.66992188e-01 -3.60107422e-03  4.61425781e-02 -1.63085938e-01
 -2.53906250e-01  1.89453125e-01 -7.51953125e-02 -5.39550781e-02
 -1.77734375e-01 -4.32128906e-02 -7.38525391e-03  1.57226562e-01
  2.53906250e-01 -1.52343750e-01 -5.27343750e-02 -1.25000000e-01
  1.54296875e-01  1.11816406e-01 -1.54418945e-02  8.97216797e-03
 -5.63964844e-02 -2.58789062e-02  1.93359375e-01  5.22460938e-02
 -1.56250000e-02 -5.68847656e-02  1.17187500e-01  6.00585938e-02
 -2.64892578e-02 -1.39648438e-01 -7.27539062e-02 -5.00488281e-02
  2.97851562e-02 -9.61914062e-02 -1.60156250e-01 -1.41601562e-01
  2.17773438e-01  2.55859375e-01 -4.58984375e-02  1.17187500e-01
 -2.46093750e-01 -7.27539062e-02 -8.69140625e-02  1.57226562e-01
 -1.88476562e-01  4.39453125e-02 -5.55419922e-03  6.93359375e-02
  1.42578125e-01 -1.20605469e-01 -1.04003906e-01 -3.41796875e-02
  1.82617188e-01 -1.29882812e-01  1.63574219e-02  3.20312500e-01
 -1.12304688e-01 -1.12915039e-02 -1.38671875e-01 -2.20703125e-01
  7.59124756e-04  3.94531250e-01  1.03515625e-01 -6.64062500e-02
 -2.67578125e-01 -2.47070312e-01 -7.27539062e-02  1.07910156e-01
  1.18652344e-01 -8.30078125e-02  6.54296875e-02 -2.94189453e-02]

In [ ]:
# Downloading the pre-trained word embedding vectors generated by the FastText method  trained on Wikipedia 2017, UMBC webbase corpus and statmt.org news datase
model = api.load("fasttext-wiki-news-subwords-300")
vec = model.get_vector("woman")
print(vec)

#Loading the pre-trained word embedding vectors created by the GloVE method trained on  Wikipedia 2014 + Gigaword 5
model = api.load("glove-wiki-gigaword-300")
vec = model.get_vector("woman")
print(vec)

###EXAMPLE 3: Computing similarity between words based on the pre-trained vector representations

In [11]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
words = "man woman kitchen football".split()
#Obtain the vectors for each word
dv=[model.get_vector(word) for word in words]
sim= np.round(cosine_similarity(dv,dv), 3)
dn = pd.DataFrame(index=words, columns=words, data=sim)
dn

            man  woman  kitchen  football
man       1.000  0.766    0.077     0.268
woman     0.766  1.000    0.138     0.121
kitchen   0.077  0.138    1.000     0.054
football  0.268  0.121    0.054     1.000

### Some examples of the semantic relations captures by the word embeddig models

In [5]:
model.most_similar(positive=["Sweden"], negative=[], topn=15, restrict_vocab=None, indexer=None)

[('Finland', 0.8084676265716553),
 ('Norway', 0.7706172466278076),
 ('Denmark', 0.7673707008361816),
 ('Swedish', 0.7404001355171204),
 ('Swedes', 0.7133285999298096),
 ('Scandinavian', 0.6518087983131409),
 ('Stena_Match_Cup', 0.6437665820121765),
 ('Netherlands', 0.6401046514511108),
 ('official_Lars_Emilsson', 0.6374117732048035),
 ('Stockholm', 0.6336992383003235),
 ('Latvia', 0.6308620572090149),
 ('Switzerland', 0.6276935935020447),
 ('Scandinavia', 0.6253065466880798),
 ('Bjorkdal_Gold_Mine', 0.6242160797119141),
 ('Linkoeping', 0.6231747269630432)]

In [6]:
model.most_similar(positive=["king", "woman"], negative=["man"], topn=15, restrict_vocab=None, indexer=None)

[('queen', 0.7118193507194519),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321839332581),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.5181134343147278),
 ('sultan', 0.5098593831062317),
 ('monarchy', 0.5087411999702454),
 ('royal_palace', 0.5087166428565979),
 ('throne', 0.5005807876586914),
 ('royal', 0.493820458650589),
 ('Princess_Sikhanyiso', 0.4936617612838745),
 ('ruler', 0.4909275770187378)]

In [7]:
model.most_similar(positive=["Spain", "Rome"], negative=["Madrid"], topn=15, restrict_vocab=None, indexer=None)

[('Italy', 0.7004685997962952),
 ('Sicily', 0.59268718957901),
 ('Greece', 0.5306450724601746),
 ('defeated_Andreas_Seppi', 0.4919793903827667),
 ('Sardinia', 0.48941102623939514),
 ("Valle_D'_Aosta", 0.48918789625167847),
 ('Lorenzago_di_Cadore', 0.48693549633026123),
 ('Malta', 0.48546910285949707),
 ('Romania', 0.4842848777770996),
 ('Paestum', 0.47937682271003723),
 ("Francesco_D'_Aniello", 0.47917160391807556),
 ('Berlioz_Harold', 0.4779238998889923),
 ('France', 0.47591346502304077),
 ('Bambino_Gesu_Hospital', 0.4755710959434509),
 ('Salonika_Greece', 0.47398701310157776)]

### EXAMPLE 4: Loading pre-trained word embedding (created by Word2Vec) from a local file

In [ ]:
# Download pretrained word embedding vectors generated by Word2Vec trained on Google News 2013 dataset
!wget http://vectors.nlpl.eu/repository/20/1.zip
#!wget http://vectors.nlpl.eu/repository/20/6.zip
!unzip 1.zip
#!unzip 6.zip

from gensim.models.keyedvectors import KeyedVectors
#Loading the pretarianed word embedding vectors from a binary file format
wordvb = KeyedVectors.load_word2vec_format('model.bin',  binary=True, limit=None)

#Loading the pretarianed word embedding vectors from a text file format
wordvt = KeyedVectors.load_word2vec_format('model.txt',  binary=False, limit=None)

### EXAMPLE 5: Loading pre-trained word embedding (created by FastText) from a local file

In [ ]:
# Download pre-trained word embedding vectors generated by FastText trained on Common Crawl and Wikipedia, in binary format
#!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.bin.gz
#from gensim.models.keyedvectors import KeyedVectors
#Loading the pre-trained word embedding vectors from a binary file format
#wordvb = KeyedVectors.load_word2vec_format('cc.en.300.bin.gz', binary=True, limit=None)

# Download pre-trained word embedding vectors generated by FastText trained on Common Crawl and Wikipedia, in text format
!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.vec.gz
#Loading the pre-trained word embedding vectors from a text file format
wordvt = KeyedVectors.load_word2vec_format('cc.en.300.vec.gz', binary=False, limit=None)

### EXAMPLE 6: Loading pre-trained word embedding (created by Glove) from a local file

In [15]:
# Download the pre-trained word embedding vectors generated by GloVe trained on a Twitter corpus
!wget https://nlp.stanford.edu/data/wordvecs/glove.twitter.27B.zip
!unzip glove.twitter.27B.zip

--2025-02-22 17:27:51--  https://nlp.stanford.edu/data/wordvecs/glove.twitter.27B.zip
Resolving nlp.stanford.edu (nlp.stanford.edu)... 171.64.67.140
Connecting to nlp.stanford.edu (nlp.stanford.edu)|171.64.67.140|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://downloads.cs.stanford.edu/nlp/data/wordvecs/glove.twitter.27B.zip [following]
--2025-02-22 17:27:51--  https://downloads.cs.stanford.edu/nlp/data/wordvecs/glove.twitter.27B.zip
Resolving downloads.cs.stanford.edu (downloads.cs.stanford.edu)... 171.64.64.22
Connecting to downloads.cs.stanford.edu (downloads.cs.stanford.edu)|171.64.64.22|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1520408741 (1.4G) [application/zip]
Saving to: ‘glove.twitter.27B.zip’

glove.twitter.27B.z 100%[===================>]   1.42G  1.94MB/s    in 5m 39s

2025-02-22 17:33:30 (4.28 MB/s) - ‘glove.twitter.27B.zip’ saved [1520408741/1520408741]

Archive:  glove.twitter.27B.zip
  inflating: glove.twitter.27B.100d.txt
  inflating: glove.twitter.27B.200d.txt
  inflating: glove.twitter.27B.25d.txt
  inflating: glove.twitter.27B.50d.txt

In [17]:
from gensim.models.keyedvectors import KeyedVectors
size=None
wordv = KeyedVectors.load_word2vec_format('glove.twitter.27B.200d.txt',  binary=False, no_header=True, limit=size)

WARNING:gensim.models.keyedvectors:duplicate word '<unk>' in word2vec file, ignoring all but first
WARNING:gensim.models.keyedvectors:duplicate word '<unk>' in word2vec file, ignoring all but first

In [18]:
wordv.get_vector("doctors")

array([ 3.1757e-01, -5.7845e-01, -3.9579e-01,  2.8347e-01,  3.1561e-01,
       -2.7203e-01,  4.9718e-01,  3.7040e-01,  5.2751e-01, -2.4206e-01,
        1.0819e-01,  7.8633e-02, -8.6085e-01, -1.6325e-01,  7.0262e-01,
       -8.0698e-01, -4.5228e-01,  6.0755e-01, -4.5933e-01, -6.6005e-01,
        4.2281e-01, -3.3672e-01,  1.4251e-01,  3.1925e-02,  6.5474e-01,
        1.2764e+00, -9.6147e-02,  8.6969e-03, -1.3257e-01, -1.2353e-01,
        4.4061e-01, -5.9514e-01,  2.0260e-01,  4.1254e-01, -1.8691e-01,
       -1.7350e-01, -3.4907e-01,  3.5320e-01,  7.1500e-01,  3.0949e-01,
        9.0643e-01, -1.2438e-01,  2.8870e-01, -6.7590e-01,  1.1703e-01,
        8.6316e-01,  1.5931e-01,  5.6584e-01,  5.5294e-01,  5.2991e-01,
       -1.5568e-01,  2.1371e-01, -4.8201e-01, -7.3439e-02, -1.7253e-01,
        4.0986e-01, -4.2577e-01,  3.2559e-01,  2.5333e-01, -9.2971e-02,
       -1.7417e-01, -2.1238e-02,  1.6682e-01, -1.4533e-01,  1.4443e-01,
        3.6025e-01,  4.6135e-01,  1.8182e-01,  3.0659e-01,  2.5208e-01,
        3.0752e-01,  2.7314e-01, -4.4798e-02, -1.7398e-01,  7.6930e-01,
        2.1097e-01, -1.0944e+00, -8.0676e-01, -5.3014e-01, -8.5994e-03,
       -2.8255e-01,  3.7482e-01,  5.7723e-01,  3.8509e-01, -1.3559e-02,
        5.9063e-02,  8.7318e-02,  1.1836e-01,  1.0707e-01, -1.0904e-01,
       -3.4731e-01, -4.2766e-01,  4.9450e-01,  3.1339e-01,  2.0813e-01,
        8.5868e-01,  3.7696e-01,  2.5186e-01,  5.1746e-01,  2.4644e-02,
       -2.7324e-02, -4.7856e-01, -1.8206e-01,  6.9097e-01, -8.8848e-02,
       -4.1520e-01,  3.6191e-01, -5.5067e-01, -9.4531e-02, -5.0433e-01,
       -2.0299e-01, -1.8888e-01, -4.6551e-01, -9.7276e-02, -1.5670e-02,
       -5.5170e-01, -8.3416e-02, -2.8747e-02,  4.4630e-03,  4.9417e-01,
        1.2216e-01, -2.2907e-03,  2.7982e-01,  5.8190e-01, -8.9627e-02,
       -3.1921e-01, -1.7253e-01,  4.8239e-01,  5.9563e-01,  2.2004e-02,
        4.5623e-03,  3.3599e-01, -5.4608e-01, -4.6767e-01, -5.6415e-01,
       -1.1997e+00, -5.9517e-01, -9.9540e-02,  1.9804e-01, -1.4410e-02,
        6.5552e-01,  7.7277e-02,  3.5186e-01,  4.3853e-01,  9.9706e-01,
       -1.0738e-01, -4.3297e-02, -2.3828e-01, -2.8216e-01, -1.0407e+00,
        2.3684e-01,  3.1421e-01, -2.5867e+00,  2.8277e-01, -2.7170e-01,
        3.0707e-01,  2.8233e-01, -1.8182e-01, -4.3584e-01,  8.3601e-01,
        1.4167e-01, -2.3354e-01,  2.3221e-02,  1.4576e-01, -1.2164e-02,
        2.6652e-01, -6.4831e-01, -2.3419e-01,  1.4106e-01, -1.0316e-01,
       -3.2973e-01,  4.0906e-01,  3.4057e-01, -2.7344e-01, -4.3773e-01,
       -3.2272e-01, -5.8950e-01, -4.3072e-01, -2.2284e-01, -5.8498e-01,
        2.8255e-01,  3.0979e-02,  5.0232e-01,  1.6135e-01,  2.8899e-01,
        8.3499e-01, -9.9400e-02, -1.6309e-02,  1.1201e-01,  6.0575e-01,
       -3.0326e-01, -5.1202e-01, -1.9586e-01, -4.2110e-02, -6.4931e-02,
       -2.8991e-01, -3.4772e-01,  1.3845e-01,  1.0407e-01,  1.9625e-01],
      dtype=float32)

### EXAMPLE 7: Loading pre-trained word embedding vectors in Spanish from a local file

In [ ]:
# Download pre-trained word embedding vectors generated by FastText trained on Common Crawl and Wikipedia, in binary format for Spanish
#!wget https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.es.300.bin.gz
#from gensim.models.keyedvectors import KeyedVectors
#Loading the pre-trained word embedding vectors from a binary file format
#wordvb = KeyedVectors.load_word2vec_format('cc.es.300.bin.gz', binary=True, limit=None)

###EXAMPLE 8: Learning word embeddings vector on a specific corpus

In [13]:
import nltk
nltk.download("punkt_tab")
from gensim.models import Word2Vec
from nltk.tokenize import word_tokenize

# Tokenize the corpus. Notice that the preprocessing and tokenization of the texts can be customized depending on the task.
tokenized_corpus = [word_tokenize(sentence.lower()) for sentence in df["text"].tolist()]
# Train the Word2Vec model
model = Word2Vec(sentences=tokenized_corpus, vector_size=100, window=5, min_count=1, workers=4)
# Get the word vector for a specific word
word_vector = model.wv["woman"]
# Most similar words to "example"
similar_words = model.wv.most_similar("woman")
print("Word vector for 'doctors':", word_vector)
print("Most similar words to 'doctors':", similar_words)
model.wv.save_word2vec_format("my-word-embedding-vectors-100d.txt", binary=False)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

Word vector for 'doctors': [-4.60996389e-01  6.57014489e-01  2.16854721e-01  1.43921807e-01
  2.99997061e-01 -1.24132895e+00  3.83461535e-01  1.76292408e+00
 -5.93351245e-01 -7.29108393e-01 -1.81596741e-01 -1.06581700e+00
 -3.05227458e-01  2.59013623e-01  3.20336819e-01 -7.88807571e-01
  5.93299866e-01 -7.02982843e-01 -3.35223973e-01 -1.66159546e+00
  4.20017600e-01  3.60404313e-01  8.54148269e-01 -3.52247298e-01
 -2.82803893e-01  2.43252981e-02 -5.56697667e-01 -3.88925552e-01
 -7.11213887e-01  5.55989183e-02  3.89182746e-01 -2.83574760e-01
  5.00123799e-01 -9.82756376e-01 -2.74456948e-01  1.07175434e+00
  2.58109599e-01 -2.60949820e-01 -4.66166228e-01 -1.14532113e+00
  1.57628432e-01 -7.01909900e-01 -5.48126996e-01  2.16419131e-01
  4.20538366e-01 -3.83250386e-01 -3.82903278e-01 -3.02622408e-01
  3.80378574e-01  3.69553924e-01  6.90584004e-01 -4.93170947e-01
 -1.87866867e-01 -7.90443853e-04 -7.00825512e-01  2.47043028e-01
  4.24603105e-01 -1.68061797e-02 -6.03567541e-01  3.50135833e-01
  2.45188609e-01 -3.82114425e-02  2.54032403e-01  9.35009308e-03
 -5.46991527e-01  1.13032293e+00  1.05970301e-01  1.49120033e+00
 -1.28504825e+00  1.03931201e+00 -1.75697535e-01  3.38270307e-01
  8.87274206e-01  1.61287516e-01  9.51349556e-01  3.38026375e-01
 -1.19562835e-01  2.99871832e-01 -3.07783395e-01 -1.17720127e-01
 -8.90826941e-01  1.20489709e-01 -1.00593138e+00  1.06901789e+00
 -2.35578343e-01 -9.78158265e-02  5.92972696e-01  9.17645752e-01
  7.25307643e-01  7.46793374e-02  1.19027781e+00  3.91635984e-01
 -8.07345510e-02  1.87618360e-01  1.44045687e+00  7.97694802e-01
  1.61676586e-01 -6.37465060e-01  1.25755221e-01 -1.79427117e-01]
Most similar words to 'doctors': [('man', 0.9997247457504272), ('a', 0.9996898174285889), ('that', 0.9995835423469543), ('like', 0.9995823502540588), ('there', 0.9995735883712769), ('she', 0.9995645880699158), ('when', 0.9995290040969849), ('because', 0.9995219111442566), ('women', 0.9994877576828003), ('be', 0.999481737613678)]

###EXAMPLE9: Obtaining the representation of a text using word embedding vectors

In [19]:
#Obtaining the words or terms in the text. This time we considered a simple whitespace splitting.
#Notice that, after split the texts, the stopwords can be removed
#dim is the dimension of the word embedding vectors.
def get_sentence_rep(text, keyedvec, dim=300):
    words= text.lower().split()
    zero_vec=np.zeros(dim)
    avg_vec=np.zeros(dim)
    total_w=0
    for w in words:
        try:
            avg_vec+=keyedvec[w]
            total_w+=1
        except:
           print(f"The word {w} is not found in the embedding matrix")
    if total_w == 0:
        return zero_vec
    return avg_vec/total_w

text= "The theory of paint indicates feelings of isolation in society"
get_sentence_rep(text, wordv, dim=200)

array([ 1.10728079e-01, -2.41359975e-03,  8.04889992e-02,  1.11822981e-02,
        1.91767388e-01,  3.35076098e-01,  2.28565097e-01, -3.53715699e-01,
       -1.99007994e-01, -1.86432800e-01,  2.90411700e-01,  1.22699997e-01,
       -1.03384201e+00, -5.28682053e-02, -1.62239797e-01,  1.69918618e-02,
        7.34258968e-02, -1.46386501e-01, -1.61766499e-01,  1.77796399e-01,
       -7.68188011e-02,  6.90893047e-02,  3.37609872e-03,  1.78887603e-01,
        6.97899006e-02,  9.02345003e-01,  1.47917901e-01,  1.19611048e-01,
       -6.53349996e-02,  3.85862952e-02,  1.16280795e-02, -2.90007303e-01,
       -1.43445700e-01, -1.44891306e-01, -1.07311800e-01, -1.09994801e-01,
        4.96960036e-02,  1.73614409e-01,  9.31910009e-02,  4.89425048e-02,
        3.69661793e-01, -2.92963043e-02,  1.39141436e-01, -1.02758892e-01,
        3.02879405e-01,  7.21744973e-02,  2.11248998e-02,  4.57060002e-03,
        8.04887941e-02, -1.71223697e-01,  1.38592820e-01, -9.52298999e-02,
        8.96099955e-04,  8.53094034e-02, -2.94926897e-01, -1.17335101e-01,
       -2.70160049e-02, -1.22442100e-01, -2.24939799e-01,  9.41265189e-02,
       -8.23267013e-02,  1.30681632e-01, -1.87494702e-01, -1.61075898e-01,
        1.62854901e-01,  4.09374496e-01,  2.01540900e-01, -7.86740096e-02,
       -8.63767993e-02,  7.20615011e-02, -7.06904389e-02, -1.18701760e-01,
       -2.32700799e-01,  7.74987062e-02,  3.92118999e-01, -6.47654016e-02,
       -3.17492940e-02, -1.83844394e-01,  2.30830695e-02, -1.61774978e-01,
        3.03410502e-01,  1.13761398e-01,  2.40076697e-01,  2.64281300e-01,
        9.93841004e-02, -9.46346011e-02, -2.29398012e-02,  1.46969989e-02,
       -1.58315796e-01,  5.95754963e-02, -1.61094993e-02,  5.62463030e-02,
        1.65553800e-01, -4.80113044e-02,  2.96348985e-02, -2.63197198e-01,
        1.27291998e-01, -3.31260792e-01,  2.14829725e-01,  1.47987109e-01,
        2.18099505e-03,  2.35969976e-02, -7.03825066e-02,  2.41437104e-01,
        1.94829997e-01, -2.75721195e-01, -1.94586024e-02, -1.84869329e-01,
       -2.58829202e-01, -2.80862001e-01,  9.25452001e-02, -3.76663990e-02,
       -5.55930994e-02, -2.80547898e-01, -2.63242475e-01,  6.29470264e-02,
       -4.75950979e-02,  8.14311666e-02, -1.58185797e-01,  2.75236005e-01,
        1.24412601e-01,  4.97517998e-02,  9.99213945e-02, -4.67403501e-01,
       -1.09999020e-02,  1.71453102e-01, -1.17502987e-02, -1.90915997e-01,
        3.43587502e-01,  5.90269893e-02,  8.38329021e-02,  1.30874803e-01,
       -7.13199982e-02,  1.95390005e-01,  1.30805703e-01, -9.03353997e-02,
        2.31111804e-01,  9.75514941e-02,  2.72530597e-01, -4.39322904e-01,
        2.88306993e-01, -1.62765001e-02, -1.54538002e-01, -6.50680047e-03,
       -1.19023201e-01,  1.26328103e-01, -2.57801297e-01, -1.06954395e-01,
       -2.77633602e-01,  2.24053298e-01,  2.98971396e-01, -3.18599999e-02,
       -4.11422099e+00, -2.63151100e-01, -9.27322092e-02, -1.94985467e-01,
        2.52592900e-01,  7.08033953e-02,  5.64811006e-03,  9.68580000e-02,
        3.58731101e-01,  2.57221805e-01, -6.87519703e-03,  5.90318987e-02,
        6.03799987e-02,  1.28106099e-01, -2.56882989e-02,  8.15680034e-02,
        2.32273300e-01, -7.04762965e-02,  2.47073303e-01,  2.27560698e-01,
        1.38978106e-01,  1.66772296e-01,  4.34669588e-02,  9.65786992e-02,
       -3.80469561e-03,  1.87006019e-02,  1.12592404e-01, -1.39541402e-01,
        8.90521999e-02,  3.39428991e-02, -1.11568098e-01, -2.09112997e-01,
       -2.81438000e-01,  2.59428624e-01, -2.33479980e-02, -1.13686029e-02,
        4.48620014e-02, -7.82363631e-02,  3.21102142e-04, -2.89151392e-01,
        6.52307960e-02,  6.66500032e-03,  8.89160007e-02,  7.29179680e-03,
        2.98561381e-01,  1.64837606e-01, -1.22482501e-01, -4.30966997e-01])